REQUEST_URL: https://api.iletimerkezi.com/v1/send-sms/json

STATIC_PARAMS:
  sender: ""
  iys: "0"
  # iysList: ""
  key: ""
  hash: ""

AMQP_QUEUE_NAME: sms
# MESSAGE_FOOTER: ""

# AMQP_CONNECTIONSTRING: amqp://guest:guest@amqpcontainer
